spring.application.name=number-one
spring.datasource.driverClassName=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/likelion_db
spring.datasource.username=root
spring.datasource.password= 7635
#{}??? ?????

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.swagger-ui.path=/swagger-ui.html

jwt.secret-key=likelion-session-jwt-secret-key-for-practice-2026

kakao.client-id=d261324965908ba251e50243dc46ddbd
kakao.client-secret=HykACFnGeWMe6z5sMZmKQ9b6bRByFacF
kakao.redirect-uri=http://localhost:8080/api/v1/auth/kakao/callback-page
kakao.token-uri=https://kauth.kakao.com/oauth/token
kakao.user-info-uri=https://kapi.kakao.com/v2/user/me